site_utilisateurs:
    resource: "@SiteUtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

site_front_office:
    resource: "@SiteFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /
